## SAMPLE YAML CONFIGURATION FILE FOR KCHIP


# Droplets Image Parameters
image:
  base_path: .

  names:
    premerge: AF405
    t0: Chip1_t0

  pixel_size: 3.25 # um/px
  size: 2048 # px
  overlap: 0.05
  well_start_image: [1,2]
  well_start_xy: [540,140]
  dyes: [0,1,2,3]  # index (start at 0) in image for dye channels
  bugs: 4       # index of bugs (start at 0) in image for dye channels
  rescale: [1,1,3,1,1]

well_mask:
  filename: kchip/well_mask.tif
  pixel_size: 8.33625 # um/px
  well_start_xy: [850,  522] # currently this is post scaling

barcodes:
  path: kchip/Notes.xlsx
  cluster:
      offset: [1200,600,600]
      points_to_cluster: 2000
      eps: 0.025
      min_samples: 6
