## TEMPLATE YAML CONFIGURATION FILE FOR U19 KCHIPS


# Droplets Image Parameters
image:
  base_path: ./data/raw/
  base_path2: ./data/raw/  # background image

  names:
    premerge: _premerge  ### SPECIFIC TO DAY ###
    t0: _tfinal ### SPECIFIC TO DAY ###

  pixel_size: 4.25 # um/px
  size: 2960 # px
  overlap: 0.1
  well_start_image: [1,2]
  well_start_xy: [540,140]
  dyes: [0,1,2]  # index (start at 0) in image for dye channels
  bugs: 3  # index of bugs (start at 0) in image for dye channels
  rescale: [1,1,2.3,1] ### SPECIFIC TO CHIP, NOW AUTOMATED ###
  # 45.5k / 33k / 20k / Reporter / 6,000
  1to1_bkg: background

well_mask:
  filename:
  pixel_size: 8.33625 # um/px
  well_start_xy: [850,  522] # currently this is post scaling

barcodes:
  path: ../../Notes-crl.xlsx
  cluster:
      offset: [0,0,0]
      points_to_cluster: 2000
      eps: 0.030
      min_samples: 2
